// <auto-generated />
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.InternalMigratons
{
    [DbContext(typeof(FUEC_DbContext))]
    [Migration("20250401230551_initPrueba")]
    partial class initPrueba
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ENTITY.Third_Party", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)");

                    b.HasKey("id");

                    b.ToTable("Third_Partys");
                });
#pragma warning restore 612, 618
        }
    }
}
